<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Vehiculo;
use App\Models\Marca;
use Illuminate\Support\Facades\DB;

class VehiculoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Obtener las marcas
        $audi = Marca::where('nombre', 'AUDI')->first();
        $chevrolet = Marca::where('nombre', 'CHEVROLET')->first();
        $honda = Marca::where('nombre', 'HONDA')->first();

        $vehiculos = [
            // VEHÍCULOS AUDI
            [
                'placa' => 'A123BCZ',
                'modelo' => 2023,
                'linea' => 'A4',
                'motor' => '2.0 TFSI',
                'cilindraje' => 2.0,
                'marca_id' => $audi->id,
                'cantidad_aceite_motor' => '5.7 litros',
                'marca_aceite' => 'Mobil 1',
                'tipo_aceite' => '5W-40',
                'filtro_aceite' => 'PH9688',
                'filtro_aire' => 'A1234',
                'cantidad_aceite_cc' => '2.5 litros',
                'marca_cc' => 'Audi Genuine',
                'tipo_aceite_cc' => 'ATF',
                'filtro_aceite_cc' => 'TF087',
                'filtro_de_enfriador' => 'TF012',
                'tipo_caja' => 'Automática 8 velocidades',
                'cantidad_aceite_diferencial' => '1.2 litros',
                'marca_aceite_d' => 'Castrol',
                'tipo_aceite_d' => '75W-90',
                'cantidad_aceite_transfer' => '1.5 litros',
                'marca_aceite_t' => 'Audi Genuine',
                'tipo_aceite_t' => '75W-140',
                'filtro_cabina' => 'CF072',
                'filtro_diesel' => 'No aplica',
                'contra_filtro_diesel' => 'No aplica',
                'candelas' => 'BKR6E-11',
                'pastillas_delanteras' => 'P06065',
                'pastillas_traseras' => 'P06070',
                'fajas' => '6PK2280',
                'aceite_hidraulico' => 'DOT 4',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'placa' => 'A456EFZ',
                'modelo' => 2022,
                'linea' => 'Q5',
                'motor' => '3.0 TDI',
                'cilindraje' => 3.0,
                'marca_id' => $audi->id,
                'cantidad_aceite_motor' => '7.5 litros',
                'marca_aceite' => 'Castrol',
                'tipo_aceite' => '5W-30',
                'filtro_aceite' => 'PH7317',
                'filtro_aire' => 'A2468',
                'cantidad_aceite_cc' => '3.2 litros',
                'marca_cc' => 'ZF',
                'tipo_aceite_cc' => 'ATF',
                'filtro_aceite_cc' => 'TF103',
                'filtro_de_enfriador' => 'TF010',
                'tipo_caja' => 'Automática 7 velocidades',
                'cantidad_aceite_diferencial' => '1.5 litros',
                'marca_aceite_d' => 'Liqui Moly',
                'tipo_aceite_d' => '80W-90',
                'cantidad_aceite_transfer' => '1.8 litros',
                'marca_aceite_t' => 'Audi Genuine',
                'tipo_aceite_t' => '75W-140',
                'filtro_cabina' => 'CF075',
                'filtro_diesel' => 'P550935',
                'contra_filtro_diesel' => 'WK731/6',
                'candelas' => 'BKR7E',
                'pastillas_delanteras' => 'P06080',
                'pastillas_traseras' => 'P06085',
                'fajas' => '6PK2300',
                'aceite_hidraulico' => 'DOT 4',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'placa' => 'A789HIZ',
                'modelo' => 2024,
                'linea' => 'A3',
                'motor' => '1.8 TFSI',
                'cilindraje' => 1.8,
                'marca_id' => $audi->id,
                'cantidad_aceite_motor' => '4.8 litros',
                'marca_aceite' => 'Shell Helix',
                'tipo_aceite' => '5W-30',
                'filtro_aceite' => 'PH3660',
                'filtro_aire' => 'A1357',
                'cantidad_aceite_cc' => '2.2 litros',
                'marca_cc' => 'Audi Genuine',
                'tipo_aceite_cc' => 'ATF',
                'filtro_aceite_cc' => 'TF090',
                'filtro_de_enfriador' => 'TF042',
                'tipo_caja' => 'Automática 6 velocidades',
                'cantidad_aceite_diferencial' => '1.0 litros',
                'marca_aceite_d' => 'Shell',
                'tipo_aceite_d' => '75W-90',
                'cantidad_aceite_transfer' => '1.2 litros',
                'marca_aceite_t' => 'Audi Genuine',
                'tipo_aceite_t' => '75W-140',
                'filtro_cabina' => 'CF070',
                'filtro_diesel' => 'No aplica',
                'contra_filtro_diesel' => 'No aplica',
                'candelas' => 'BKR6E',
                'pastillas_delanteras' => 'P06060',
                'pastillas_traseras' => 'P06065',
                'fajas' => '6PK2260',
                'aceite_hidraulico' => 'DOT 4',
                'created_at' => now(),
                'updated_at' => now()
            ],

            // VEHÍCULOS CHEVROLET
            [
                'placa' => 'C123XYY',
                'modelo' => 2023,
                'linea' => 'Spark',
                'motor' => '1.2 MPFi',
                'cilindraje' => 1.2,
                'marca_id' => $chevrolet->id,
                'cantidad_aceite_motor' => '3.5 litros',
                'marca_aceite' => 'ACDelco',
                'tipo_aceite' => '5W-30',
                'filtro_aceite' => 'PF457G',
                'filtro_aire' => 'A258C',
                'cantidad_aceite_cc' => '2.0 litros',
                'marca_cc' => 'ACDelco',
                'tipo_aceite_cc' => 'Dexron VI',
                'filtro_aceite_cc' => 'TF101',
                'filtro_de_enfriador' => 'TF012',
                'tipo_caja' => 'Manual 5 velocidades',
                'cantidad_aceite_diferencial' => '0.8 litros',
                'marca_aceite_d' => 'ACDelco',
                'tipo_aceite_d' => '80W-90',
                'cantidad_aceite_transfer' => 'No aplica',
                'marca_aceite_t' => 'No aplica',
                'tipo_aceite_t' => 'No aplica',
                'filtro_cabina' => 'CF100',
                'filtro_diesel' => 'No aplica',
                'contra_filtro_diesel' => 'No aplica',
                'candelas' => '41-110',
                'pastillas_delanteras' => '171-1085',
                'pastillas_traseras' => '171-1090',
                'fajas' => '4PK950',
                'aceite_hidraulico' => 'DOT 3',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'placa' => 'C456ABZ',
                'modelo' => 2022,
                'linea' => 'Tracker',
                'motor' => '1.4 Turbo',
                'cilindraje' => 1.4,
                'marca_id' => $chevrolet->id,
                'cantidad_aceite_motor' => '4.2 litros',
                'marca_aceite' => 'Mobil Super',
                'tipo_aceite' => '5W-30',
                'filtro_aceite' => 'PF48',
                'filtro_aire' => 'A3185C',
                'cantidad_aceite_cc' => '2.2 litros',
                'marca_cc' => 'ACDelco',
                'tipo_aceite_cc' => 'Dexron VI',
                'filtro_aceite_cc' => 'TF102',
                'filtro_de_enfriador' => 'TF012',
                'tipo_caja' => 'Automática 6 velocidades',
                'cantidad_aceite_diferencial' => '1.1 litros',
                'marca_aceite_d' => 'ACDelco',
                'tipo_aceite_d' => '75W-90',
                'cantidad_aceite_transfer' => 'No aplica',
                'marca_aceite_t' => 'No aplica',
                'tipo_aceite_t' => 'No aplica',
                'filtro_cabina' => 'CF118',
                'filtro_diesel' => 'No aplica',
                'contra_filtro_diesel' => 'No aplica',
                'candelas' => '41-122',
                'pastillas_delanteras' => '171-1100',
                'pastillas_traseras' => '171-1105',
                'fajas' => '6PK1760',
                'aceite_hidraulico' => 'DOT 4',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'placa' => 'C789DEZ',
                'modelo' => 2021,
                'linea' => 'Sail',
                'motor' => '1.4 MPFi',
                'cilindraje' => 1.4,
                'marca_id' => $chevrolet->id,
                'cantidad_aceite_motor' => '3.8 litros',
                'marca_aceite' => 'Chevron',
                'tipo_aceite' => '10W-30',
                'filtro_aceite' => 'PF457G',
                'filtro_aire' => 'A1234C',
                'cantidad_aceite_cc' => '2.1 litros',
                'marca_cc' => 'ACDelco',
                'tipo_aceite_cc' => 'Dexron VI',
                'filtro_aceite_cc' => 'TF100',
                'filtro_de_enfriador' => 'TF012',
                'tipo_caja' => 'Manual 5 velocidades',
                'cantidad_aceite_diferencial' => '0.9 litros',
                'marca_aceite_d' => 'ACDelco',
                'tipo_aceite_d' => '80W-90',
                'cantidad_aceite_transfer' => 'No aplica',
                'marca_aceite_t' => 'No aplica',
                'tipo_aceite_t' => 'No aplica',
                'filtro_cabina' => 'CF105',
                'filtro_diesel' => 'No aplica',
                'contra_filtro_diesel' => 'No aplica',
                'candelas' => '41-115',
                'pastillas_delanteras' => '171-1095',
                'pastillas_traseras' => '171-1100',
                'fajas' => '5PK1130',
                'aceite_hidraulico' => 'DOT 3',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'placa' => 'C012GHZ',
                'modelo' => 2023,
                'linea' => 'Onix Turbo',
                'motor' => '1.0 Turbo',
                'cilindraje' => 1.0,
                'marca_id' => $chevrolet->id,
                'cantidad_aceite_motor' => '4.0 litros',
                'marca_aceite' => 'Petrobras',
                'tipo_aceite' => '5W-30',
                'filtro_aceite' => 'PF64',
                'filtro_aire' => 'A3186C',
                'cantidad_aceite_cc' => '2.3 litros',
                'marca_cc' => 'ACDelco',
                'tipo_aceite_cc' => 'Dexron VI',
                'filtro_aceite_cc' => 'TF104',
                'filtro_de_enfriador' => 'TF012',
                'tipo_caja' => 'Automática 6 velocidades',
                'cantidad_aceite_diferencial' => '1.0 litros',
                'marca_aceite_d' => 'ACDelco',
                'tipo_aceite_d' => '75W-90',
                'cantidad_aceite_transfer' => 'No aplica',
                'marca_aceite_t' => 'No aplica',
                'tipo_aceite_t' => 'No aplica',
                'filtro_cabina' => 'CF120',
                'filtro_diesel' => 'No aplica',
                'contra_filtro_diesel' => 'No aplica',
                'candelas' => '41-125',
                'pastillas_delanteras' => '171-1110',
                'pastillas_traseras' => '171-1115',
                'fajas' => '6PK1780',
                'aceite_hidraulico' => 'DOT 4',
                'created_at' => now(),
                'updated_at' => now()
            ],

            // VEHÍCULOS HONDA
            [
                'placa' => 'H123KLZ',
                'modelo' => 2023,
                'linea' => 'Civic',
                'motor' => '2.0 i-VTEC',
                'cilindraje' => 2.0,
                'marca_id' => $honda->id,
                'cantidad_aceite_motor' => '3.7 litros',
                'marca_aceite' => 'Honda Genuine',
                'tipo_aceite' => '0W-20',
                'filtro_aceite' => '15400-PLM-A02',
                'filtro_aire' => '17220-P2G-003',
                'cantidad_aceite_cc' => '2.5 litros',
                'marca_cc' => 'Honda ATF',
                'tipo_aceite_cc' => 'Honda ATF DW-1',
                'filtro_aceite_cc' => 'TF105',
                'filtro_de_enfriador' => 'TF012',
                'tipo_caja' => 'CVT',
                'cantidad_aceite_diferencial' => '0.8 litros',
                'marca_aceite_d' => 'Honda Dual Pump',
                'tipo_aceite_d' => 'Honda ATF',
                'cantidad_aceite_transfer' => 'No aplica',
                'marca_aceite_t' => 'No aplica',
                'tipo_aceite_t' => 'No aplica',
                'filtro_cabina' => '80292-SDA-A01',
                'filtro_diesel' => 'No aplica',
                'contra_filtro_diesel' => 'No aplica',
                'candelas' => 'IZFR6K11',
                'pastillas_delanteras' => '45022-TBA-A01',
                'pastillas_traseras' => '43022-TBC-A01',
                'fajas' => '6PK1770',
                'aceite_hidraulico' => 'Honda Brake Fluid',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'placa' => 'H456NOZ',
                'modelo' => 2022,
                'linea' => 'CR-V',
                'motor' => '1.5 Turbo',
                'cilindraje' => 1.5,
                'marca_id' => $honda->id,
                'cantidad_aceite_motor' => '3.8 litros',
                'marca_aceite' => 'Honda Ultra',
                'tipo_aceite' => '0W-20',
                'filtro_aceite' => '15400-R5A-003',
                'filtro_aire' => '17220-69A-003',
                'cantidad_aceite_cc' => '3.1 litros',
                'marca_cc' => 'Honda ATF',
                'tipo_aceite_cc' => 'Honda ATF DW-1',
                'filtro_aceite_cc' => 'TF106',
                'filtro_de_enfriador' => 'TF012',
                'tipo_caja' => 'Automática 9 velocidades',
                'cantidad_aceite_diferencial' => '0.9 litros',
                'marca_aceite_d' => 'Honda Dual Pump',
                'tipo_aceite_d' => 'Honda ATF',
                'cantidad_aceite_transfer' => '1.4 litros',
                'marca_aceite_t' => 'Honda Genuine',
                'tipo_aceite_t' => '75W-140',
                'filtro_cabina' => '80292-TLA-A01',
                'filtro_diesel' => 'No aplica',
                'contra_filtro_diesel' => 'No aplica',
                'candelas' => 'IZFR7K11',
                'pastillas_delanteras' => '45022-TVA-A01',
                'pastillas_traseras' => '43022-TVA-A01',
                'fajas' => '6PK1790',
                'aceite_hidraulico' => 'Honda Brake Fluid',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'placa' => 'H789QRZ',
                'modelo' => 2024,
                'linea' => 'Accord',
                'motor' => '2.0 Hybrid',
                'cilindraje' => 2.0,
                'marca_id' => $honda->id,
                'cantidad_aceite_motor' => '4.2 litros',
                'marca_aceite' => 'Honda Hybrid',
                'tipo_aceite' => '0W-16',
                'filtro_aceite' => '15400-PLM-A02',
                'filtro_aire' => '17220-69A-003',
                'cantidad_aceite_cc' => '2.8 litros',
                'marca_cc' => 'Honda ATF',
                'tipo_aceite_cc' => 'Honda ATF DW-1',
                'filtro_aceite_cc' => 'TF107',
                'filtro_de_enfriador' => 'TF012',
                'tipo_caja' => 'e-CVT',
                'cantidad_aceite_diferencial' => '0.7 litros',
                'marca_aceite_d' => 'Honda Dual Pump',
                'tipo_aceite_d' => 'Honda ATF',
                'cantidad_aceite_transfer' => 'No aplica',
                'marca_aceite_t' => 'No aplica',
                'tipo_aceite_t' => 'No aplica',
                'filtro_cabina' => '80292-TGB-A01',
                'filtro_diesel' => 'No aplica',
                'contra_filtro_diesel' => 'No aplica',
                'candelas' => 'IZFR8K11',
                'pastillas_delanteras' => '45022-TZA-A01',
                'pastillas_traseras' => '43022-TZA-A01',
                'fajas' => '6PK1763',
                'aceite_hidraulico' => 'Honda Brake Fluid',
                'created_at' => now(),
                'updated_at' => now()
            ]
        ];

        // Insertar vehículos usando DB facade para mejor performance
        DB::table('vehiculo')->insert($vehiculos);

        $this->command->info('✅ 10 vehículos insertados: 3 AUDI, 4 CHEVROLET, 3 HONDA');
        $this->command->info('📝 Todos los campos han sido llenados completamente');
    }
}